version: '3.3'

services:
  mysql:
    container_name: "mysql"
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'school'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql-dump:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
#    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:db

